using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.DataAccess;
using DevExpress.DashboardCommon;

namespace mnd.UI.Modules.Dashboard
{
    public partial class Dashboard1 : DevExpress.DashboardCommon.Dashboard
    {
        public Dashboard1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }
    }
}
